# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Job_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Job_company', models.CharField(max_length=100)),
                ('Job_position', models.CharField(max_length=100)),
                ('Job_address', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('job_add', 'Apply a new job'), ('job_delete', 'Delete this position'), ('job_modify', 'Modify this job'), ('job_search', 'Search job')),
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_Faculty', models.BooleanField(default=False)),
                ('is_Student', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Pro_IF', models.IntegerField(primary_key=True, serialize=False)),
                ('Pro_start', models.DateTimeField()),
                ('Pro_end', models.DateTimeField()),
                ('Pro_description', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('pro_add', 'Add a new project'), ('pro_delete', 'Delete this project'), ('pro_modify', 'Modify this project'), ('pro_search', 'Search projects')),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapps.MyUser')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
            },
            bases=('myapps.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapps.MyUser')),
            ],
            options={
                'verbose_name': 'staff',
            },
            bases=('myapps.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapps.MyUser')),
                ('Stu_start', models.DateTimeField(blank=True, null=True)),
                ('Stu_end', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Windsor', max_length=20)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('SK', 'Saskatchewan'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('YT', 'Yukon'), ('NU', 'Nunabut')], default='ON', max_length=2)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
            bases=('myapps.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Fac_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.Faculty'),
        ),
        migrations.AddField(
            model_name='project',
            name='Stu_ID',
            field=models.ManyToManyField(to='myapps.Student'),
        ),
    ]
