# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Pro_IF',
            new_name='Pro_ID',
        ),
    ]
