# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_auto_20170821_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Pro_title',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
