# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_project_pro_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Pro_title',
        ),
    ]
