# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_remove_project_pro_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Pro_title',
            field=models.CharField(default='Project title', max_length=200),
        ),
    ]
