# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_auto_20170821_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Stu_ID',
            field=models.ManyToManyField(to='myapps.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Pro_title',
            field=models.CharField(default='Project title', max_length=200, verbose_name='title'),
        ),
    ]
