# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_auto_20170822_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Fac_position',
            field=models.CharField(choices=[('Director', 'Director'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Instructor', 'Instructor')], default='Instructor', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('NS', 'Nova Scotia'), ('SK', 'Saskatchewan'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('YT', 'Yukon'), ('NU', 'Nunabut')], default='ON', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='Stu_ID',
            field=models.ManyToManyField(to='myapps.Student', verbose_name='Student name'),
        ),
    ]
